// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAADI9DMS5RrlJTZmEiYaljSo0m7bHS8Qc',
    appId: '1:890023903348:web:da07b7a7beec1e62341121',
    messagingSenderId: '890023903348',
    projectId: 'musicapp-4a88a',
    authDomain: 'musicapp-4a88a.firebaseapp.com',
    storageBucket: 'musicapp-4a88a.firebasestorage.app',
    measurementId: 'G-677SPXD1M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqrPcmCFJq8nIZi0TqROIOzAF3P2AyJ2c',
    appId: '1:890023903348:android:6e0fd825e003b65d341121',
    messagingSenderId: '890023903348',
    projectId: 'musicapp-4a88a',
    storageBucket: 'musicapp-4a88a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOIoxK80_8LD9hX_GM2L9PepajfDd6R8E',
    appId: '1:890023903348:ios:85c5a3fe3bc2ba97341121',
    messagingSenderId: '890023903348',
    projectId: 'musicapp-4a88a',
    storageBucket: 'musicapp-4a88a.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOIoxK80_8LD9hX_GM2L9PepajfDd6R8E',
    appId: '1:890023903348:ios:85c5a3fe3bc2ba97341121',
    messagingSenderId: '890023903348',
    projectId: 'musicapp-4a88a',
    storageBucket: 'musicapp-4a88a.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAADI9DMS5RrlJTZmEiYaljSo0m7bHS8Qc',
    appId: '1:890023903348:web:190e132f36c4484e341121',
    messagingSenderId: '890023903348',
    projectId: 'musicapp-4a88a',
    authDomain: 'musicapp-4a88a.firebaseapp.com',
    storageBucket: 'musicapp-4a88a.firebasestorage.app',
    measurementId: 'G-L308R0HPPK',
  );
}
